set(headers ${headers}
	src/Compatibility.h
	src/Dialogue.h
	src/GlobalHistory.h
	src/Hooks.h
	src/Hotkeys.h
	src/ImGui/Backend/imgui_impl_win32.h
	src/ImGui/Graphics.h
	src/ImGui/IconsFonts.h
	src/ImGui/Renderer.h
	src/ImGui/Styles.h
	src/ImGui/Util.h
	src/Input.h
	src/LocalHistory.h
	src/PCH.h
	src/Papyrus.h
	src/Settings.h
	src/Translation.h
)
