set(sources ${sources}
	src/Compatibility.cpp
	src/Dialogue.cpp
	src/GlobalHistory.cpp
	src/Hooks.cpp
	src/Hotkeys.cpp
	src/ImGui/Backend/imgui_impl_win32.cpp
	src/ImGui/Graphics.cpp
	src/ImGui/IconsFonts.cpp
	src/ImGui/Renderer.cpp
	src/ImGui/Styles.cpp
	src/ImGui/Util.cpp
	src/Input.cpp
	src/LocalHistory.cpp
	src/PCH.cpp
	src/Papyrus.cpp
	src/Settings.cpp
	src/Translation.cpp
	src/main.cpp
)
